/*
 * This displays the splash screen for few seconds on the screen
 * and loads the login screen
 * 
*/
package booklendingsystemlaunch;

import security.Login;

/**
 *
 * @author philip
 */
public class Splash extends javax.swing.JFrame {

    private Login login;
 

    /**
     * Creates new form Splash
     */
    public Splash() {
        
        initComponents();
        setLocationRelativeTo(null);
        
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadingValue = new javax.swing.JLabel();
        loadingBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadingValue.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        loadingValue.setForeground(new java.awt.Color(204, 0, 204));
        loadingValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loadingValue.setText("99%");
        loadingValue.setRequestFocusEnabled(false);
        loadingValue.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(loadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 423, 60, 20));

        loadingBar.setBackground(new java.awt.Color(255, 255, 255));
        loadingBar.setBorder(null);
        getContentPane().add(loadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 800, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/splashScreen.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public javax.swing.JProgressBar loadingBar;
    public javax.swing.JLabel loadingValue;
    // End of variables declaration//GEN-END:variables
    
}
