/*
 * This is the API that handles the Login in to the system
 */
package security;

import database.ConnectDb;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import models.MainApi;
import models.MainApiUser;

/**
 *
 * @author philip
 */
public class Login extends javax.swing.JFrame {

    private PreparedStatement pst;
    private Connection con;
    private Statement stmt;
    private ResultSet rs;
    private String sql;
    private String query;
    public static String loginName;
    private int xMouse;
    private int yMouse;

    /**
     * Creates new form Login
     */
    public Login() {
        sql = "SELECT * FROM admin";//admin table
        initComponents();
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(btnLogin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pswPassword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cboLoginType = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 100, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel7.setText("Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setText("Username");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel5.setText("Login Type");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        btnLogin.setToolTipText("Press Enter key to Login or Click here");
        btnLogin.setBorder(null);
        btnLogin.setBorderPainted(false);
        btnLogin.setContentAreaFilled(false);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 350, 85, 26));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loginok.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        pswPassword.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        getContentPane().add(pswPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 180, 40));

        txtUsername.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtUsername.setOpaque(true);
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 180, 30));

        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel3MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel3MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setToolTipText("Close Application");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 0, 30, 20));

        cboLoginType.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        cboLoginType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Login type-", "admin login", "users login" }));
        cboLoginType.setToolTipText("Select user name.");
        cboLoginType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLoginTypeItemStateChanged(evt);
            }
        });
        cboLoginType.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cboLoginTypePropertyChange(evt);
            }
        });
        getContentPane().add(cboLoginType, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 180, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login_image_icon.png"))); // NOI18N
        jLabel2.setBorder(null);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        //this button login to the system and open the main Api of the system
        requestLogin();

    }//GEN-LAST:event_btnLoginActionPerformed

    private void requestLogin() {

        if (cboLoginType.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Please select Login type");
        } else if (cboLoginType.getSelectedIndex() == 1) {
            if (pswPassword.getPassword().length == 0) {
                JOptionPane.showMessageDialog(null, "Password  empty");
                pswPassword.requestFocus();
            } else {
                char[] pass;
                pass = pswPassword.getPassword();
                String password = String.copyValueOf(pass);
                String username = txtUsername.getText();
                if (validate_admin_login(username, password)) {
                    dispose();//close the login screen and open a new one
                    MainApi api = new MainApi();
                    api.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Wrong Pass word");
                    pswPassword.setText("");
                    pswPassword.requestFocus();
                }
            }
        } else if (cboLoginType.getSelectedIndex() == 2) {
            if (pswPassword.getPassword().length == 0) {
                JOptionPane.showMessageDialog(null, "Password empty");
                pswPassword.requestFocus();
            }
            if (txtUsername.getText().length() == 0) {
                JOptionPane.showMessageDialog(null, "Username empty");
                txtUsername.requestFocus();
            } else {
                char[] pass;
                pass = pswPassword.getPassword();
                String password = String.copyValueOf(pass);
                String username = txtUsername.getText();
                if (validate_user_login(username, password)) {
                    dispose();//close the login screen and open a new one
                    MainApiUser login = new MainApiUser();
                    login.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Wrong Password or username");
                    txtUsername.setText("");
                    pswPassword.setText("");
                    txtUsername.requestFocus();
                }
            }
        }
    }

    private boolean validate_admin_login(String username, String password) {
        return username.equalsIgnoreCase("admin") && (password.equalsIgnoreCase("admin"));
    }

    private boolean validate_user_login(String username, String password) {
        String sql = "SELECT * FROM admin WHERE username =? and password =?";
        try {
            con = ConnectDb.connect();
            pst = con.prepareStatement(sql);

            pst.setString(1, username);
            pst.setString(2, password);
            rs = pst.executeQuery();

            if (rs.next()) {
                return true;
            } else {
                return false;
            }

        } catch (Exception e) {
            e.printStackTrace();
            return false;
        } finally {
            try {
                pst.close();
                rs.close();
                con.close();
            } catch (Exception e2) {
                e2.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error ....");
            }
        }
    }
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void cboLoginTypePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cboLoginTypePropertyChange

    }//GEN-LAST:event_cboLoginTypePropertyChange

    private void cboLoginTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLoginTypeItemStateChanged
        if (cboLoginType.getSelectedIndex() == 1) {
            txtUsername.setEditable(false);
            txtUsername.setText("admin");
            pswPassword.requestFocus();
        } else {
            txtUsername.setEditable(true);
            txtUsername.setText("");
            txtUsername.requestFocus();
        }
    }//GEN-LAST:event_cboLoginTypeItemStateChanged

    private void jLabel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jLabel3MouseDragged

    private void jLabel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseMoved
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabel3MouseMoved

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cboLoginType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField pswPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
