/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package models;

import database.ConnectDb;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author philip
 */
public class CreateLibrarian extends javax.swing.JFrame {

    private Admin admin;
    private int xMouse;
    private int yMouse;
    private Connection con;
    private PreparedStatement pst;
    private ResultSet rs;

    /**
     * Creates new form CreateLibrarian
     */
    public CreateLibrarian() {
        admin = new Admin();
        initComponents();
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(btnSave);
        rdbtnMale.setActionCommand("Male");
        rdbtnFemale.setActionCommand("Female");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rdbtnFemale = new javax.swing.JRadioButton();
        rdbtnMale = new javax.swing.JRadioButton();
        txtSurname = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        txtUsername = new javax.swing.JTextField();
        txtMiddlename = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPhoneno = new javax.swing.JTextField();
        txtFirstname = new javax.swing.JTextField();
        pswPassword = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel13MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel13MouseMoved(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 40));

        jButton1.setText("Reset");
        jButton1.setToolTipText("Reset entries in fields");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, -1, -1));

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 153));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Create New Librarian Account");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 480, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete-icon.png"))); // NOI18N
        jLabel11.setToolTipText("Close ");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.setRequestFocusEnabled(false);
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 6, -1, -1));

        buttonGroup1.add(rdbtnFemale);
        rdbtnFemale.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        rdbtnFemale.setText("Female");
        getContentPane().add(rdbtnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        buttonGroup1.add(rdbtnMale);
        rdbtnMale.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        rdbtnMale.setText("Male");
        getContentPane().add(rdbtnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));
        getContentPane().add(txtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 190, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 620, 10));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 620, 10));
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 190, 30));
        getContentPane().add(txtMiddlename, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 190, 30));
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 460, 30));

        txtPhoneno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhonenoKeyTyped(evt);
            }
        });
        getContentPane().add(txtPhoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 150, 30));
        getContentPane().add(txtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 150, 30));
        getContentPane().add(pswPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 190, -1));

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel10.setText("Address:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setText("Surname:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setText("Firstname:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setText("Middlename:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setText("Gender:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel5.setText("Phone Number:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setText("Username:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel7.setText("Password:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        btnSave.setText("Create");
        btnSave.setToolTipText("Save entries to table");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/librarian-create.png"))); // NOI18N
        jLabel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel9MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        //validate entries are entered
        if (txtSurname.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Surname not Provided.");
            txtSurname.requestFocus();
        } else if (txtFirstname.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Firstname not Provided.");
            txtFirstname.requestFocus();
        } else if (txtMiddlename.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Middlename not Provided.");
            txtMiddlename.requestFocus();
        } else if (txtAddress.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Address not Provided.");
            txtAddress.requestFocus();
        } else if (txtPhoneno.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Phone number is required.");
            txtPhoneno.requestFocus();

        } else if (txtUsername.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Password is required.");
            txtUsername.requestFocus();

        } else if (pswPassword.getPassword().length == 0) {
            JOptionPane.showMessageDialog(null, "Password is required.");
            pswPassword.requestFocus();

        } else if (buttonGroup1.isSelected(null)) {
            JOptionPane.showMessageDialog(null, "Select  Gender");

        } else {
            //test validity of username
            String username = txtUsername.getText();
            if (!username_Exist(username)) {
                try {
                    admin = getData();

                    try {

                        int result;
                        result = admin.createNewRecord(admin);

                        if (result == 1) {
                            JOptionPane.showMessageDialog(null, "Successfully created a new Librarian....");

                            this.dispose();

                        } else {
                            JOptionPane.showMessageDialog(null, "Problemm creating a Librarian......");
                        }
                    } catch (Exception e1) {
                        e1.printStackTrace();

                    }
                } catch (Exception e2) {

                }//end of try

            } else {
                JOptionPane.showMessageDialog(null, "User name already in used");
                txtUsername.requestFocus();
            }
//enf of test validity

        }//end of else if
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        dispose();//close the dialog box
    }//GEN-LAST:event_jLabel11MouseClicked

    private void txtPhonenoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhonenoKeyTyped
        //validate phone entry column
        char c = evt.getKeyChar();
        if (!((Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_SPACE))) {
            getToolkit().beep();
            txtPhoneno.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Please use digits (0---9) only ");
            txtPhoneno.setBackground(Color.white);
            evt.consume();

        } else {
            if (txtPhoneno.getText().length() >= 11) {
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, "Local Phone number should not exceed 11 characters");
                evt.consume();
            }
        }
    }//GEN-LAST:event_txtPhonenoKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clearFields();//clears the fields
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel9MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseDragged

    }//GEN-LAST:event_jLabel9MouseDragged

    private void jLabel13MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseMoved
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabel13MouseMoved

    private void jLabel13MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jLabel13MouseDragged

    private Admin getData() {
        admin.setSurname(txtSurname.getText());
        admin.setPassword(pswPassword.getText());
        admin.setFirstname(txtFirstname.getText());
        admin.setMiddlename(txtMiddlename.getText());
        admin.setGender(buttonGroup1.getSelection().getActionCommand());
        admin.setAddress(txtAddress.getText());
        admin.setPhoneno(txtPhoneno.getText());
        admin.setUsername(txtUsername.getText());

        return admin;

    }

    private void clearFields() {
        txtSurname.setText("");
        pswPassword.setText("");
        txtFirstname.setText("");
        txtMiddlename.setText("");
        buttonGroup1.clearSelection();
        txtAddress.setText("");
        txtPhoneno.setText("");
        txtUsername.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateLibrarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreateLibrarian dialog = new CreateLibrarian();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField pswPassword;
    private javax.swing.JRadioButton rdbtnFemale;
    private javax.swing.JRadioButton rdbtnMale;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtMiddlename;
    private javax.swing.JTextField txtPhoneno;
    private javax.swing.JTextField txtSurname;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private boolean username_Exist(String username) {
        String sql = "SELECT * FROM admin WHERE username =?";
        try {
            con = ConnectDb.connect();
            pst = con.prepareStatement(sql);

            pst.setString(1, username);

            rs = pst.executeQuery();

            if (rs.next()) {
                return true;
            } else {
                return false;
            }

        } catch (Exception e) {
            e.printStackTrace();
            return false;
        } finally {
            try {
                pst.close();
                rs.close();
                con.close();
            } catch (Exception e2) {
                e2.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error ....");
            }
            //return false;
        }
    }
}
