/*
 * This is the main API for the Book LEnding System used by the Librarian with less functionality
 */
package models;

import security.Login;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import reports.Reports;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;


/**
 *
 * @author philip
 */
public class MainApiUser extends javax.swing.JFrame {

    private UserApi_User userApi = new UserApi_User();
    private BookApi_User bookApi = new BookApi_User();
    private Login login = new Login();
    private CheckInBook checkIn;
    private CheckOutBook checkOut;
    private CheckInToRenewBook checkToRenew;
   
    private CreateLibrarian librarian;
    private UpdateBook updateBook;
    private UpdateUserInformation updateUser;
    private Reports reports;

    public MainApiUser() {
        initComponents();
        setDefaultCloseOperation(3);
        setScreen();
        getContentPane().setBackground(Color.WHITE);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/bg.png"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image, 0, 0, getWidth(),getHeight(),this);
            }
        };
        jPanel1 = new javax.swing.JPanel();
        createNewBook = new javax.swing.JLabel();
        createNewUser = new javax.swing.JLabel();
        borrowBook = new javax.swing.JLabel();
        returnBook = new javax.swing.JLabel();
        renewBook = new javax.swing.JLabel();
        createLibrarian1 = new javax.swing.JLabel();
        updateBookInfor = new javax.swing.JLabel();
        updateUsersInfor = new javax.swing.JLabel();
        viewReports = new javax.swing.JLabel();
        aboutUs = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        desktopPane = new javax.swing.JDesktopPane(){
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.setColor(Color.white);
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 13, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/main_heading.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 8, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/version.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/library_black.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete-icon.png"))); // NOI18N
        close.setToolTipText("Close Application");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel2.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, -1, -1));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minimise.png"))); // NOI18N
        minimize.setToolTipText("minimize screen");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        jPanel2.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 10, -1, -1));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1350, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jPanel2.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 116, 1350, 25));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 25, 5));

        createNewBook.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        createNewBook.setForeground(new java.awt.Color(51, 0, 153));
        createNewBook.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        createNewBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/book.png"))); // NOI18N
        createNewBook.setText("<html><center>Create<br> book</center></html>");
        createNewBook.setToolTipText("Click to add new book  to the Library");
        createNewBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createNewBook.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        createNewBook.setName(""); // NOI18N
        createNewBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createNewBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createNewBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createNewBookMouseExited(evt);
            }
        });
        jPanel1.add(createNewBook);

        createNewUser.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        createNewUser.setForeground(new java.awt.Color(51, 0, 153));
        createNewUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        createNewUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        createNewUser.setText("<html>Create<br>User</html>");
        createNewUser.setToolTipText("Click to register new member to to the Library");
        createNewUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createNewUser.setName(""); // NOI18N
        createNewUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createNewUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createNewUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createNewUserMouseExited(evt);
            }
        });
        jPanel1.add(createNewUser);

        borrowBook.setForeground(new java.awt.Color(51, 0, 153));
        borrowBook.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        borrowBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/book4.png"))); // NOI18N
        borrowBook.setText("<html><center><strong>Borrow<br>Book</center></strong></html>");
        borrowBook.setToolTipText("Borrow Book(s)");
        borrowBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borrowBook.setName(""); // NOI18N
        borrowBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrowBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                borrowBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                borrowBookMouseExited(evt);
            }
        });
        jPanel1.add(borrowBook);

        returnBook.setForeground(new java.awt.Color(51, 0, 153));
        returnBook.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        returnBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return.png"))); // NOI18N
        returnBook.setText("<html><center><strong>Return <br>Book</center></strong></html>");
        returnBook.setToolTipText("Returns borrow book to the Library");
        returnBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnBook.setName(""); // NOI18N
        returnBook.setRequestFocusEnabled(false);
        returnBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                returnBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                returnBookMouseExited(evt);
            }
        });
        jPanel1.add(returnBook);

        renewBook.setForeground(new java.awt.Color(51, 0, 153));
        renewBook.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        renewBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/book2.png"))); // NOI18N
        renewBook.setText("<html><center><strong>Renew <br>Book</center></strong></html>");
        renewBook.setToolTipText("Renew borrowed book ");
        renewBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        renewBook.setName(""); // NOI18N
        renewBook.setRequestFocusEnabled(false);
        renewBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                renewBookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                renewBookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                renewBookMouseExited(evt);
            }
        });
        jPanel1.add(renewBook);

        createLibrarian1.setForeground(new java.awt.Color(51, 0, 153));
        createLibrarian1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        createLibrarian1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/librarian-icon.png"))); // NOI18N
        createLibrarian1.setText("<html><center><strong>Create<br> Librarian</strong></center></html>");
        createLibrarian1.setToolTipText("Admin function to create new Librarian");
        createLibrarian1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createLibrarian1.setEnabled(false);
        createLibrarian1.setFocusable(false);
        createLibrarian1.setName(""); // NOI18N
        createLibrarian1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createLibrarian1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createLibrarian1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createLibrarian1MouseExited(evt);
            }
        });
        jPanel1.add(createLibrarian1);

        updateBookInfor.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        updateBookInfor.setForeground(new java.awt.Color(51, 0, 153));
        updateBookInfor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        updateBookInfor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update1.png"))); // NOI18N
        updateBookInfor.setText("<html>Update Book's<br>information</html>");
        updateBookInfor.setToolTipText("Click to update and delete book");
        updateBookInfor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateBookInfor.setEnabled(false);
        updateBookInfor.setName(""); // NOI18N
        updateBookInfor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBookInforMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateBookInforMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateBookInforMouseExited(evt);
            }
        });
        jPanel1.add(updateBookInfor);

        updateUsersInfor.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        updateUsersInfor.setForeground(new java.awt.Color(51, 0, 153));
        updateUsersInfor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        updateUsersInfor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Modify.png"))); // NOI18N
        updateUsersInfor.setText("<html>Update User's<br> Information</html>");
        updateUsersInfor.setToolTipText("Click to Update or delete User");
        updateUsersInfor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateUsersInfor.setEnabled(false);
        updateUsersInfor.setName(""); // NOI18N
        updateUsersInfor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateUsersInforMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateUsersInforMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateUsersInforMouseExited(evt);
            }
        });
        jPanel1.add(updateUsersInfor);

        viewReports.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        viewReports.setForeground(new java.awt.Color(51, 0, 153));
        viewReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/report.png"))); // NOI18N
        viewReports.setText("<html>View <br>Reports</html>");
        viewReports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewReports.setName(""); // NOI18N
        viewReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewReportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewReportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewReportsMouseExited(evt);
            }
        });
        jPanel1.add(viewReports);

        aboutUs.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        aboutUs.setForeground(new java.awt.Color(51, 0, 153));
        aboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/about_us.png"))); // NOI18N
        aboutUs.setText("About Us");
        aboutUs.setToolTipText("Information about developers");
        aboutUs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutUs.setName(""); // NOI18N
        aboutUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutUsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutUsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutUsMouseExited(evt);
            }
        });
        jPanel1.add(aboutUs);

        logout.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 0, 51));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        logout.setText("Logout");
        logout.setToolTipText("Log out of the system");
        logout.setBorder(null);
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.setName(""); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        jPanel1.add(logout);

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 1160, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1346, 130));

        desktopPane.setForeground(new java.awt.Color(255, 255, 255));
        desktopPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                desktopPaneMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Book Lending System");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        desktopPane.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel5)
                .addContainerGap(406, Short.MAX_VALUE))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel5)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        getContentPane().add(desktopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 144, 1350, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        exitSystem();//closes the application
    }//GEN-LAST:event_closeMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        setState(MainApiUser.ICONIFIED);//minimizes the screen of the application
    }//GEN-LAST:event_minimizeMouseClicked

    private void createNewBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createNewBookMouseClicked
        //this calls the internal JFrame into the desktop pane
        desktopPane.removeAll();
        desktopPane.repaint();
        desktopPane.add(bookApi);
        try {
            bookApi.setMaximum(true);
        } catch (PropertyVetoException e) {

        }
        bookApi.show();
    }//GEN-LAST:event_createNewBookMouseClicked

    private void createNewUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createNewUserMouseClicked
        //this calls the internal JFrame of the UserApi into the desktop of the MainApi
        desktopPane.removeAll();
        desktopPane.repaint();
        desktopPane.add(userApi);
        try {
            userApi.setMaximum(true);
        } catch (PropertyVetoException e) {

        }
        userApi.show();
    }//GEN-LAST:event_createNewUserMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        //logs out user from the system and return to login screen
        dispose();
        
        login.setVisible(true);//loads the login screen
    }//GEN-LAST:event_logoutMouseClicked

    private void aboutUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutUsMouseClicked
        AboutUs aboutus = new AboutUs();
        aboutus.setVisible(true);
    }//GEN-LAST:event_aboutUsMouseClicked

    private void returnBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnBookMouseClicked
        checkIn = new CheckInBook();
        checkIn.setVisible(true);
    }//GEN-LAST:event_returnBookMouseClicked

    private void borrowBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowBookMouseClicked
        checkOut = new CheckOutBook();
        checkOut.setVisible(true);
    }//GEN-LAST:event_borrowBookMouseClicked

    private void renewBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_renewBookMouseClicked
        checkToRenew = new CheckInToRenewBook();
        checkToRenew.setVisible(true);
    }//GEN-LAST:event_renewBookMouseClicked

    private void createLibrarian1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createLibrarian1MouseClicked
       //librarian = new CreateLibrarian();
       //librarian.setVisible(true);
        //newDept = new NewDepartment();
        //newDept.setVisible(true);
    }//GEN-LAST:event_createLibrarian1MouseClicked

    private void updateBookInforMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBookInforMouseClicked
        ///updateBook = new UpdateBook();
        ///updateBook.setVisible(true);
    }//GEN-LAST:event_updateBookInforMouseClicked

    private void updateUsersInforMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateUsersInforMouseClicked
        //updateUser = new UpdateUserInformation();
        //updateUser.setVisible(true);
    }//GEN-LAST:event_updateUsersInforMouseClicked

    private void viewReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewReportsMouseClicked
        reports = new Reports();
        reports.setVisible(true);
    }//GEN-LAST:event_viewReportsMouseClicked

    private void createNewBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createNewBookMouseEntered
        createNewBook.setForeground(Color.PINK);
    }//GEN-LAST:event_createNewBookMouseEntered

    private void createNewBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createNewBookMouseExited
        createNewBook.setForeground(Color.getColor("myBlue", 330099));
    }//GEN-LAST:event_createNewBookMouseExited

    private void createNewUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createNewUserMouseEntered
        createNewUser.setForeground(Color.pink);
    }//GEN-LAST:event_createNewUserMouseEntered

    private void createNewUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createNewUserMouseExited
        createNewUser.setForeground(Color.getColor("myBlue",330099));
    }//GEN-LAST:event_createNewUserMouseExited

    private void borrowBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowBookMouseEntered
        borrowBook.setForeground(Color.pink);
    }//GEN-LAST:event_borrowBookMouseEntered

    private void borrowBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowBookMouseExited
        borrowBook.setForeground(Color.getColor("myBlue",330099));
    }//GEN-LAST:event_borrowBookMouseExited

    private void returnBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnBookMouseEntered
        returnBook.setForeground(Color.PINK);
    }//GEN-LAST:event_returnBookMouseEntered

    private void returnBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnBookMouseExited
       returnBook.setForeground(Color.getColor("myBlue", 330099));
    }//GEN-LAST:event_returnBookMouseExited

    private void renewBookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_renewBookMouseEntered
       renewBook.setForeground(Color.PINK);
    }//GEN-LAST:event_renewBookMouseEntered

    private void renewBookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_renewBookMouseExited
        renewBook.setForeground(Color.getColor("myBlue", 330099));
    }//GEN-LAST:event_renewBookMouseExited

    private void createLibrarian1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createLibrarian1MouseEntered
        createLibrarian1.setForeground(Color.PINK);
    }//GEN-LAST:event_createLibrarian1MouseEntered

    private void createLibrarian1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createLibrarian1MouseExited
        createLibrarian1.setForeground(Color.getColor("myBlue", 330099));
    }//GEN-LAST:event_createLibrarian1MouseExited

    private void updateBookInforMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBookInforMouseEntered
        updateBookInfor.setForeground(Color.PINK);
    }//GEN-LAST:event_updateBookInforMouseEntered

    private void updateBookInforMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBookInforMouseExited
        updateBookInfor.setForeground(Color.getColor("myBlue", 330099));
    }//GEN-LAST:event_updateBookInforMouseExited

    private void updateUsersInforMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateUsersInforMouseEntered
        updateUsersInfor.setForeground(Color.PINK);
    }//GEN-LAST:event_updateUsersInforMouseEntered

    private void updateUsersInforMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateUsersInforMouseExited
        updateUsersInfor.setForeground(Color.getColor("myBlue", 330099));
    }//GEN-LAST:event_updateUsersInforMouseExited

    private void viewReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewReportsMouseEntered
       viewReports.setForeground(Color.PINK);
    }//GEN-LAST:event_viewReportsMouseEntered

    private void viewReportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewReportsMouseExited
       viewReports.setForeground(Color.getColor("myBlue", 330099));
    }//GEN-LAST:event_viewReportsMouseExited

    private void aboutUsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutUsMouseEntered
        aboutUs.setForeground(Color.PINK);
    }//GEN-LAST:event_aboutUsMouseEntered

    private void aboutUsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutUsMouseExited
        aboutUs.setForeground(Color.getColor("myBlue", 330099));
    }//GEN-LAST:event_aboutUsMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setForeground(Color.PINK);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setForeground(Color.RED);
    }//GEN-LAST:event_logoutMouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        desktopPane.removeAll();
        desktopPane.repaint();
        desktopPane.add(bookApi);
        bookApi.show();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void desktopPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desktopPaneMouseClicked
        desktopPane.removeAll();
        desktopPane.repaint();
        desktopPane.add(bookApi);
        bookApi.show();
    }//GEN-LAST:event_desktopPaneMouseClicked

    private void exitSystem() {//general method to clos the application exits and closes the Application
        System.exit(0);
    }

    private void setScreen() {
        //This method sets the screen of any pc to maximum size
        //gets the size of the screen

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        //determines the height of the task bar so that the display wont cover the taskbar

        Insets scnMax = Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration());
        int taskBarSize = scnMax.bottom;
        //available size of the screen

        setSize(screenSize.width, screenSize.height - taskBarSize);
        setLocation(screenSize.width - getWidth(), screenSize.height - taskBarSize - getHeight());

    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApiUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApiUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApiUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApiUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApiUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutUs;
    private javax.swing.JLabel borrowBook;
    private javax.swing.JLabel close;
    private javax.swing.JLabel createLibrarian1;
    private javax.swing.JLabel createNewBook;
    private javax.swing.JLabel createNewUser;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel renewBook;
    private javax.swing.JLabel returnBook;
    private javax.swing.JLabel updateBookInfor;
    private javax.swing.JLabel updateUsersInfor;
    private javax.swing.JLabel viewReports;
    // End of variables declaration//GEN-END:variables
    
}
