/*
API meant for the Librarian functionality to create a new user in the Library
*/

package models;

import database.ConnectDb;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

public class UserApi_User extends javax.swing.JInternalFrame {

    private String dateRegistered;//private string to store Date entry
    private DefaultTableModel model;
    private Connection con;
    private ResultSet rs;
    private Statement st;
    private String sql, query;
    private User user;

    public UserApi_User() {
        user = new User();//instantiates the user class
        sql = "SELECT * FROM department";//creates a query to load data into Department combobox
        removeGUITitle();
        initComponents();//initilizes all generated components
        getContentPane().setBackground(Color.white);
        user.loadValuesFromTable(sql, cboDepartment);//loads department into combo box
        Show_Users_In_Table();//load records from ddatabase into table 
        //defines values for radio buttons
        rdbtnMale.setActionCommand("Male");
        rdbtnFemale.setActionCommand("Female");
        rdbtnAcademic.setActionCommand("Academic");
        rdbtnNonAcademicStaff.setActionCommand("Non Academic");
        rdbtnStudent.setActionCommand("Student");
    }

    /**
     *  This method is called from within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtSurname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cboDepartment = new javax.swing.JComboBox<>();
        txtAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rdbtnAcademic = new javax.swing.JRadioButton();
        dateChooser = new com.toedter.calendar.JDateChooser();
        txtMiddlename = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rdbtnNonAcademicStaff = new javax.swing.JRadioButton();
        txtRegNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFirstname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rdbtnStudent = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        rdbtnMale = new javax.swing.JRadioButton();
        rdbtnFemale = new javax.swing.JRadioButton();
        btnNewDept = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        search_panel = new javax.swing.JPanel();
        panel_1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtSearchFirstname = new javax.swing.JTextField();
        txtSearchCat = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtSearchMiddlename = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtSearchPhoneNo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txtSearchGender = new javax.swing.JTextField();
        txtDateReg = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtSearchAddress = new javax.swing.JTextField();
        txtSearchDepartment = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtSearchSurname = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtSearchIdentity = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1250, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("User Category:");

        txtSurname.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtSurname.setForeground(new java.awt.Color(0, 3, 178));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("<html>Personal Identity <br>Card Number</html>:");

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Dete Registered:");

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Surname:");

        cboDepartment.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        cboDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Department--" }));

        txtAddress.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(0, 3, 178));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Phone No:");

        buttonGroup2.add(rdbtnAcademic);
        rdbtnAcademic.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        rdbtnAcademic.setText("Academic Staff");

        dateChooser.setDateFormatString("yyyy-MM-dd");

        txtMiddlename.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtMiddlename.setForeground(new java.awt.Color(0, 3, 178));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Address:");

        buttonGroup2.add(rdbtnNonAcademicStaff);
        rdbtnNonAcademicStaff.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        rdbtnNonAcademicStaff.setText("Non Academic");

        txtRegNo.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtRegNo.setForeground(new java.awt.Color(0, 3, 178));
        txtRegNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRegNoKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Middlename:");

        txtFirstname.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtFirstname.setForeground(new java.awt.Color(0, 3, 178));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Department:");

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Gender:");

        buttonGroup2.add(rdbtnStudent);
        rdbtnStudent.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        rdbtnStudent.setText("Student");
        rdbtnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnStudentActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Firstname:");

        txtPhone.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(0, 3, 178));
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneKeyTyped(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save-icon.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.setBorderPainted(false);
        btnSave.setContentAreaFilled(false);
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        clearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clear.png"))); // NOI18N
        clearButton.setText("Clear");
        clearButton.setBorderPainted(false);
        clearButton.setContentAreaFilled(false);
        clearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbtnMale);
        rdbtnMale.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        rdbtnMale.setText("Male");

        buttonGroup1.add(rdbtnFemale);
        rdbtnFemale.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        rdbtnFemale.setText("Female");

        btnNewDept.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        btnNewDept.setText("<html>Add New<br> Department</html>");
        btnNewDept.setToolTipText("Click to create Department");
        btnNewDept.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNewDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewDeptActionPerformed(evt);
            }
        });

        btnRefresh.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(102, 0, 204));
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh_icon.png"))); // NOI18N
        btnRefresh.setText("<html>Refresh<br>Dept</html>");
        btnRefresh.setBorderPainted(false);
        btnRefresh.setContentAreaFilled(false);
        btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbtnStudent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbtnAcademic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbtnNonAcademicStaff)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(clearButton)
                        .addGap(32, 32, 32)
                        .addComponent(btnSave)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(62, 62, 62)
                                    .addComponent(jLabel7))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addComponent(jLabel4))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addComponent(jLabel5))
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cboDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNewDept))
                            .addComponent(txtRegNo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMiddlename)
                            .addComponent(txtFirstname)
                            .addComponent(txtAddress)
                            .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(rdbtnMale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbtnFemale))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegNo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3))
                    .addComponent(txtMiddlename, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel7)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbtnMale)
                            .addComponent(rdbtnFemale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnNewDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(rdbtnStudent)
                    .addComponent(rdbtnAcademic)
                    .addComponent(rdbtnNonAcademicStaff))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave)
                    .addComponent(clearButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));

        table.setBackground(new java.awt.Color(173, 216, 230));
        table.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        table.setForeground(new java.awt.Color(0, 0, 204));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Id", "Surname", "Firstname", "Department", "Phone No.", "Date Registered"
            }
        ));
        table.setFillsViewportHeight(true);
        table.setName("table"); // NOI18N
        table.setShowHorizontalLines(true);
        table.setShowVerticalLines(true);
        scrollPane.setViewportView(table);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );

        search_panel.setBackground(new java.awt.Color(255, 255, 255));
        search_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));

        panel_1.setBackground(new java.awt.Color(249, 255, 255));
        panel_1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panel_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Surname:");
        panel_1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        txtSearchFirstname.setBackground(new java.awt.Color(220, 220, 220));
        txtSearchFirstname.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtSearchFirstname.setForeground(new java.awt.Color(0, 0, 153));
        txtSearchFirstname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panel_1.add(txtSearchFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 140, -1));

        txtSearchCat.setBackground(new java.awt.Color(220, 220, 220));
        txtSearchCat.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtSearchCat.setForeground(new java.awt.Color(0, 0, 153));
        txtSearchCat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panel_1.add(txtSearchCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 176, 176, -1));

        jLabel15.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Gender:");
        panel_1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        txtSearchMiddlename.setBackground(new java.awt.Color(220, 220, 220));
        txtSearchMiddlename.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtSearchMiddlename.setForeground(new java.awt.Color(0, 0, 153));
        panel_1.add(txtSearchMiddlename, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 151, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update1.png"))); // NOI18N
        jButton3.setText("Update");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panel_1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, -1));

        jLabel20.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("User Category:");
        panel_1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 180, -1, -1));

        txtSearchPhoneNo.setBackground(new java.awt.Color(220, 220, 220));
        txtSearchPhoneNo.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtSearchPhoneNo.setForeground(new java.awt.Color(0, 0, 153));
        txtSearchPhoneNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSearchPhoneNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchPhoneNoKeyTyped(evt);
            }
        });
        panel_1.add(txtSearchPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 190, -1));

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("<html>First<br>name:</html>");
        panel_1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        jLabel19.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Dete Registered:");
        panel_1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete.png"))); // NOI18N
        jButton4.setText("Delete");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panel_1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        txtSearchGender.setBackground(new java.awt.Color(220, 220, 220));
        txtSearchGender.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtSearchGender.setForeground(new java.awt.Color(0, 0, 153));
        txtSearchGender.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panel_1.add(txtSearchGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 51, 110, -1));

        txtDateReg.setBackground(new java.awt.Color(220, 220, 220));
        txtDateReg.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtDateReg.setForeground(new java.awt.Color(0, 0, 153));
        txtDateReg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panel_1.add(txtDateReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 176, 148, -1));

        jLabel17.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Department:");
        panel_1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 134, -1, -1));

        jLabel18.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Phone No:");
        panel_1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 134, -1, -1));

        jLabel14.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Middlename:");
        panel_1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        txtSearchAddress.setBackground(new java.awt.Color(220, 220, 220));
        txtSearchAddress.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtSearchAddress.setForeground(new java.awt.Color(0, 0, 153));
        txtSearchAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panel_1.add(txtSearchAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 460, -1));

        txtSearchDepartment.setBackground(new java.awt.Color(220, 220, 220));
        txtSearchDepartment.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtSearchDepartment.setForeground(new java.awt.Color(0, 0, 153));
        txtSearchDepartment.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panel_1.add(txtSearchDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 130, 196, -1));

        jLabel16.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Address:");
        panel_1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txtSearchSurname.setBackground(new java.awt.Color(220, 220, 220));
        txtSearchSurname.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtSearchSurname.setForeground(new java.awt.Color(0, 0, 153));
        panel_1.add(txtSearchSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 130, -1));

        jLabel21.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel21.setText("Personal Identity No");
        panel_1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtSearchIdentity.setBackground(new java.awt.Color(220, 220, 220));
        txtSearchIdentity.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        txtSearchIdentity.setForeground(new java.awt.Color(0, 0, 153));
        panel_1.add(txtSearchIdentity, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 140, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        jButton5.setToolTipText("Click to seach");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        txtSearch.setBackground(new java.awt.Color(255, 204, 204));
        txtSearch.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchFocusLost(evt);
            }
        });
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchMouseClicked(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 204));
        jLabel11.setText("Please enter user identity: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addContainerGap())
        );

        javax.swing.GroupLayout search_panelLayout = new javax.swing.GroupLayout(search_panel);
        search_panel.setLayout(search_panelLayout);
        search_panelLayout.setHorizontalGroup(
            search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_panelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(panel_1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        search_panelLayout.setVerticalGroup(
            search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search_panelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(search_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyTyped
        //validates phone entry
        validatePhoneEntry(evt);
    }//GEN-LAST:event_txtPhoneKeyTyped
    private void validatePhoneEntry(java.awt.event.KeyEvent evt) {
        //This method validates phone number inputs and ensures that it is only number and not more than 11 digits
        char c = evt.getKeyChar();
        if (!((Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_SPACE))) {
            getToolkit().beep();
            txtPhone.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Please use digits (0---9) only ");
            txtPhone.setBackground(Color.white);
            evt.consume();

        } else {
            if (txtPhone.getText().length() >= 11) {
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, "Local Phone number should not exceed 11 characters");
                evt.consume();
            }
        }
    }

    private ArrayList<User> getUsersList() {

        // creates an arraylist to load data from the database 
        ArrayList<User> usersList = new ArrayList<User>();
        con = ConnectDb.connect();

        String query = "SELECT userid, surname, firstname,department,phoneno,dateregistered FROM  users ";

        try {
            st = con.createStatement();
            rs = st.executeQuery(query);

            while (rs.next()) {
                user = new User(Integer.parseInt(rs.getString("userID")), rs.getString("surname"),
                        rs.getString("firstname"), rs.getString("department"), rs.getString("phoneno"),
                        rs.getString("dateRegistered"));
                usersList.add(user);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        return usersList;
    }// end of getUserList


    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        //This ensures that no entry required is left blank
        addNewDataToTable();

    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        //ensures entry for search operation is digit
        char c = evt.getKeyChar();
        if (!((Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtSearchKeyTyped

    private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
        txtSearch.setText("");//clears the search box
        clearFieldsData();//resets the fields to null

    }//GEN-LAST:event_txtSearchMouseClicked

    private void txtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusLost
        if (!txtSearch.getText().equals("")) {
            searchUser();
        }
    }//GEN-LAST:event_txtSearchFocusLost


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //updates information about a user and update table's data
        if (!txtSearchIdentity.getText().equals("")) {
            try {
                user = getData();
                int reply = JOptionPane.showConfirmDialog(null,
                        "Do you really want to Update the record with UserID " + txtSearch.getText() + "?",
                        "Confirm Record Update", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (reply == JOptionPane.YES_OPTION) {
                    user.UpdateUser(user); // update selected fields
                    JOptionPane.showMessageDialog(null, "Successfully Updated..........");
                    txtSearch.setText("");

                    clearFieldsData();
                    model.setRowCount(0);// reset user's table on the form
                    Show_Users_In_Table();// append the newly created to the

                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Not successful......");
                
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please search for user user to proceed");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtSearchPhoneNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchPhoneNoKeyTyped
        //validate the phone entry to ensure correct data is used
        validatePhoneEntry(evt);
    }//GEN-LAST:event_txtSearchPhoneNoKeyTyped

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clearFields();//clears the entry of the fields
    }//GEN-LAST:event_clearButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //deletes data from the database
        deletsData();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnNewDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewDeptActionPerformed
//        
        addNewCourse();
    }//GEN-LAST:event_btnNewDeptActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed

        user.loadValuesFromTable(sql, cboDepartment);

    }//GEN-LAST:event_btnRefreshActionPerformed

    private void txtRegNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegNoKeyTyped
        convertToUppercase(evt);//converts entries to upper case
    }//GEN-LAST:event_txtRegNoKeyTyped

    private void rdbtnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnStudentActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (!txtSearch.getText().equals("")) {
            searchUser();
        } else {
            JOptionPane.showMessageDialog(null, "Empty search string, please provide search string");

        }


    }//GEN-LAST:event_jButton5ActionPerformed

    private void clearFieldsData() {
        //clears the fields
        txtSearchAddress.setText("");
        txtSearchIdentity.setText("");
        txtSearchSurname.setText("");
        txtSearchCat.setText("");
        txtSearchDepartment.setText("");
        txtSearchFirstname.setText("");
        txtSearchGender.setText("");
        txtSearchMiddlename.setText("");
        txtSearchPhoneNo.setText("");
        txtDateReg.setText("");
    }

    private void deletsData() {
        if (!txtSearchIdentity.getText().equals("")) {
            try {

                int reply = JOptionPane.showConfirmDialog(null,
                        "Do you really want to Delete the record with UserID " + txtSearch.getText() + "?",
                        "Confirm Record Deletion", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (reply == JOptionPane.OK_OPTION) {
                    String query = "DELETE FROM users WHERE userid = " + txtSearch.getText();
                    user.deleteUser(query, "Deleted");
                    txtSearch.setText("");
                    panel_1.setVisible(false);
                    model.setRowCount(0);// reset user's table on the form
                    Show_Users_In_Table();// append the newly created to the
                    clearFieldsData();//resets the fields to null
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Not successful......");// TODO:

            }
        } else {
            JOptionPane.showMessageDialog(null, "Please search for user to proceed");
        }
    }

    private User getData() {
        //gets values from the panel_1 for delete and update operations
        //user = new User();
        user.setUserID(Integer.parseInt(txtSearch.getText()));
        user.setIdcardno(txtSearchIdentity.getText());
        user.setDepartment(txtSearchDepartment.getText());
        user.setSurname(txtSearchSurname.getText());
        user.setMiddlename(txtSearchMiddlename.getText());
        user.setAddress(txtSearchAddress.getText());
        user.setFirstname(txtSearchFirstname.getText());
        user.setPhoneno(txtSearchPhoneNo.getText());
        user.setGender(txtSearchGender.getText());
        user.setUserCategory(txtSearchCat.getText());
        user.setDateRegistered(txtDateReg.getText());

        return user;
    }

    private void Show_Users_In_Table() /*
	 * displays users in the table
     */ {
        ArrayList<User> list = getUsersList();
        model = (DefaultTableModel) table.getModel();
        Object[] row = new Object[6];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getUserID();
            row[1] = list.get(i).getSurname();
            row[2] = list.get(i).getFirstname();
            row[3] = list.get(i).getDepartment();
            row[4] = list.get(i).getPhoneno();
            row[5] = list.get(i).getDateRegistered();

            model.addRow(row);
        }
    }// end of Show_Users_in_Table method

    private void clearFields() {
        //resets the entries of the fields to null
        txtSurname.setText(null);
        txtRegNo.setText(null);
        txtAddress.setText(null);
        buttonGroup2.clearSelection();
        txtMiddlename.setText(null);
        txtFirstname.setText(null);
        txtPhone.setText(null);
        cboDepartment.setSelectedIndex(0);
        buttonGroup1.clearSelection();
        dateChooser.setDate(null);

    }// end of clearFields method

    private User getDetailData() {
        //get values from the form to be added to the user table
        user.setSurname(txtSurname.getText());
        user.setIdcardno(txtRegNo.getText());
        user.setFirstname(txtFirstname.getText());
        user.setMiddlename(txtMiddlename.getText());
        user.setGender(buttonGroup1.getSelection().getActionCommand());
        user.setAddress(txtAddress.getText());
        user.setDepartment(cboDepartment.getSelectedItem().toString());
        user.setPhoneno(txtPhone.getText());
        user.setUserCategory(buttonGroup2.getSelection().getActionCommand());

        // format the text from the Calendar
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");

        try {

            dateRegistered = format.format(dateChooser.getDate());

        } catch (Exception e) {
            e.printStackTrace();
        }
        user.setDateRegistered(dateRegistered);

        return user;
    }

    private void removeGUITitle() {
        //set off the title bar of internaljframe
        BasicInternalFrameUI frame = (BasicInternalFrameUI) this.getUI();
        frame.setNorthPane(null);
    }

    private void addNewDataToTable() {
        //creates new record and save to disk
        if (txtSurname.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Surname not Provided.");
            txtSurname.requestFocus();
        } else if (txtFirstname.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Firstname not Provided.");
            txtFirstname.requestFocus();
        } else if (txtMiddlename.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Middlename not Provided.");
            txtMiddlename.requestFocus();
        } else if (txtAddress.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Address not Provided.");
            txtAddress.requestFocus();
        } else if (txtPhone.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Phone number is required.");
            txtPhone.requestFocus();
        } else if (buttonGroup2.isSelected(null)) {
            JOptionPane.showMessageDialog(null, "Select user Category.");

        } else if (cboDepartment.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Select user's Department.");

        } else if (buttonGroup1.isSelected(null)) {
            JOptionPane.showMessageDialog(null, "Select User's Gender");

        } else if (dateChooser.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Select select regitration date");

        } else {
            try {
                user = getDetailData();

                try {

                    int result = user.createNewUser(user);

                    if (result == 1) {
                        JOptionPane.showMessageDialog(null, "Successfully created a new User....");
                        clearFields();
                        model.setRowCount(0);// reset user's table on the form
                        Show_Users_In_Table();// append the newly created to the table

                    } else {
                        JOptionPane.showMessageDialog(null, "Problemm creating a user......");
                    }
                } catch (Exception e1) {
                    e1.printStackTrace();

                }
            } catch (Exception e2) {

            }
        }
    }

    private void addNewCourse() {
        JDialog dialog = new JDialog();
        JTextField field = new JTextField();
        JButton saveDepartment = new JButton("Save");
        JLabel l = new JLabel("Add Department");
        saveDepartment.addActionListener((ActionEvent e) -> {
            //do insert here

            String query = "INSERT INTO `department`(`deptdescription`) VALUES ('" + field.getText() + "')";

            String message = " Created ";
            if (field.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Empty fields");
                field.requestFocus();
            } else {
                executeQuery(query, message);
                field.setText("");
                dialog.hide();
            }
        });
        setLayout(dialog.getContentPane(), field, saveDepartment, l);
        dialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dialog.add(field);
        dialog.add(saveDepartment);
        dialog.setLocationRelativeTo(null);

        dialog.setTitle("Add new Department");
        dialog.pack();
        dialog.show();

//       dialog.
    }

    private void executeQuery(String query, String message) {
        con = ConnectDb.connect();

        try {
            st = con.createStatement();
            if ((st.executeUpdate(query)) == 1) {

                JOptionPane.showMessageDialog(null, "Data " + message + " Succefully");
            } else {
                JOptionPane.showMessageDialog(null, "Data Not " + message);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * Set layout for the dialog popup
     *
     * @param container contentpane of the dialog
     * @param txtDept
     * @param jButton1
     * @param jLabel1
     */
    private void setLayout(Container container, Component txtDept, Component jButton1, Component jLabel1) {
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(container);
        container.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(7, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtDept, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtDept, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addContainerGap(8, Short.MAX_VALUE))
        );
    }

    private void searchUser() {
        int id = Integer.parseInt(txtSearch.getText());
        int userNo;
        boolean found = false;

        try {
            con = ConnectDb.connect();
            st = con.createStatement();

            String sql = "SELECT * FROM users WHERE userid = " + id + "";

            rs = st.executeQuery(sql);

            rs.next();
            userNo = rs.getInt("userid");

            if (userNo == id) {
                panel_1.setVisible(true);
                found = true;
                txtSearchDepartment.setText("" + rs.getString("department"));
                txtSearchSurname.setText("" + rs.getString("surname"));
                txtSearchIdentity.setText("" + rs.getString("useridcardno"));
                txtSearchMiddlename.setText("" + rs.getString("middlename"));
                txtSearchAddress.setText("" + rs.getString("address"));
                txtSearchFirstname.setText("" + rs.getString("firstname"));
                txtSearchPhoneNo.setText("" + rs.getString("phoneno"));
                txtSearchGender.setText("" + rs.getString("gender"));
                txtSearchCat.setText("" + rs.getString("usercategory"));
                txtDateReg.setText("" + rs.getString("dateregistered"));

            } else {
                found = false;
            }
        } catch (SQLException sqlex) {
            if (found == false) {
                // display warning message
                JOptionPane.showMessageDialog(this, "Record not Found.");
                txtSearch.setText("");
                txtSearch.requestFocus();
            }

        }
    }

    private void convertToUppercase(KeyEvent evt) {
        char c = evt.getKeyChar();
        if (Character.isLowerCase(c)) {
            evt.setKeyChar(Character.toUpperCase(c));
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewDept;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cboDepartment;
    private javax.swing.JButton clearButton;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panel_1;
    private javax.swing.JRadioButton rdbtnAcademic;
    private javax.swing.JRadioButton rdbtnFemale;
    private javax.swing.JRadioButton rdbtnMale;
    private javax.swing.JRadioButton rdbtnNonAcademicStaff;
    private javax.swing.JRadioButton rdbtnStudent;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel search_panel;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDateReg;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtMiddlename;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtRegNo;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearchAddress;
    private javax.swing.JTextField txtSearchCat;
    private javax.swing.JTextField txtSearchDepartment;
    private javax.swing.JTextField txtSearchFirstname;
    private javax.swing.JTextField txtSearchGender;
    private javax.swing.JTextField txtSearchIdentity;
    private javax.swing.JTextField txtSearchMiddlename;
    private javax.swing.JTextField txtSearchPhoneNo;
    private javax.swing.JTextField txtSearchSurname;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables

}
